### ISSUE TITLE
New version of redis insights doesnt support streams

### ISSUE THREAD

**Issue by EvsWorld** [redislabs-training/node-js-crash-course#11]
It seems that the latest version of redis insights doesn't support streams. Is there some way i can get the version of redis insights that Simon is using in the videos? Thanks.

**Comment by simonprickett** [comment]
Hi there - you can get v1.11 of RedisInsight here... make sure to select it from the "RedisInsight" version dropdown:

https://redis.com/redis-enterprise/redis-insight/

Streams support is coming to RedisInsight 2.x in the near future too.
