### ISSUE TITLE
Update `docker-compose.yml` to use the Redis Stack container.

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/node-js-crash-course#12]
Update the `docker-compose.yml` so that it uses the `redis/redis-stack` container rather than the `redismod` container.  You should be able to remove the `entrypoint` from the file as it will no longer be needed.

Test the demo application with your modified container to make sure that you can run it and interact with it.  Ensure that data in Redis persists between container restarts.

This is part of our participation in Hacktoberfest 2022. Learn how to complete this issue here: https://redis.io/community/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

If you're interested in taking this issue on, please mention @simonprickett and @SuzeShardlow in the comments and ask to be assigned.

**Comment by mohdimran25** [comment]
Hello @simonprickett and @SuzeShardlow I would like to work on this issue.

Can you Assign it to me?

I will open a pull request within two days.

**Comment by SuzeShardlow** [comment]
Hi @mohdimran25, I've assigned this to you!  Have fun with it, and we look forward to seeing your PR.
