### ISSUE TITLE
Amend README to point to the actual course pages.

### ISSUE THREAD

**Issue by simonprickett** [redislabs-training/node-js-crash-course#4]
The `README.md` file doesn't have a link to the course pages... amend this file so that where it says "This is the source code repository for the Node.js Redis Crash Course", the text "Node.js Redis Crash Course" becomes a link to https://developer.redis.com/develop/node/node-crash-course

This is part of our participation in Hacktoberfest 2021. Learn how to complete this issue here: https://developer.redis.com/hacktoberfest/

Need help or want to talk to us? Join us on Discord where we have a dedicated Hacktoberfest channel: https://discord.gg/ueQwKUh5Z3

**Comment by simonprickett** [comment]
@scottajevans I've assigned this to you.

**Comment by scottajevans** [comment]
@simonprickett thank you, sorry - I have already created a PR. Hope this is okay!
